//
//  PizzaPlannerStyleKit.swift
//  PizzaPlanner
//
//  Created by Scott Gardner on 12/24/16.
//  Copyright © 2016 (null). All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//



import UIKit

public class PizzaPlannerStyleKit : NSObject {

    //// Cache

    private struct Cache {
        static var imageOfFavorite: UIImage?
        static var favoriteTargets: [AnyObject]?
    }

    //// Drawing Methods

    public dynamic class func drawFavorite(frame targetFrame: CGRect = CGRect(x: 0, y: 0, width: 26, height: 26), resizing: ResizingBehavior = .aspectFit) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()!
        
        //// Resize to Target Frame
        context.saveGState()
        let resizedFrame: CGRect = resizing.apply(rect: CGRect(x: 0, y: 0, width: 26, height: 26), target: targetFrame)
        context.translateBy(x: resizedFrame.minX, y: resizedFrame.minY)
        context.scaleBy(x: resizedFrame.width / 26, y: resizedFrame.height / 26)


        //// Color Declarations
        let color = UIColor(red: 0.894, green: 0.733, blue: 0.427, alpha: 1.000)

        //// Star Drawing
        let starPath = UIBezierPath()
        starPath.move(to: CGPoint(x: 13, y: 2))
        starPath.addLine(to: CGPoint(x: 16.52, y: 9.15))
        starPath.addLine(to: CGPoint(x: 24.41, y: 10.29))
        starPath.addLine(to: CGPoint(x: 18.7, y: 15.85))
        starPath.addLine(to: CGPoint(x: 20.05, y: 23.71))
        starPath.addLine(to: CGPoint(x: 13, y: 19.99))
        starPath.addLine(to: CGPoint(x: 5.95, y: 23.71))
        starPath.addLine(to: CGPoint(x: 7.3, y: 15.85))
        starPath.addLine(to: CGPoint(x: 1.59, y: 10.29))
        starPath.addLine(to: CGPoint(x: 9.48, y: 9.15))
        starPath.close()
        color.setFill()
        starPath.fill()
        
        context.restoreGState()

    }

    //// Generated Images

    public dynamic class var imageOfFavorite: UIImage {
        if Cache.imageOfFavorite != nil {
            return Cache.imageOfFavorite!
        }

        UIGraphicsBeginImageContextWithOptions(CGSize(width: 26, height: 26), false, 0)
            PizzaPlannerStyleKit.drawFavorite()

        Cache.imageOfFavorite = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()

        return Cache.imageOfFavorite!
    }

    //// Customization Infrastructure

    @IBOutlet dynamic var favoriteTargets: [AnyObject]! {
        get { return Cache.favoriteTargets }
        set {
            Cache.favoriteTargets = newValue
            for target: AnyObject in newValue {
                let _ = target.perform(NSSelectorFromString("setImage:"), with: PizzaPlannerStyleKit.imageOfFavorite)
            }
        }
    }




    @objc public enum ResizingBehavior: Int {
        case aspectFit /// The content is proportionally resized to fit into the target rectangle.
        case aspectFill /// The content is proportionally resized to completely fill the target rectangle.
        case stretch /// The content is stretched to match the entire target rectangle.
        case center /// The content is centered in the target rectangle, but it is NOT resized.

        public func apply(rect: CGRect, target: CGRect) -> CGRect {
            if rect == target || target == CGRect.zero {
                return rect
            }

            var scales = CGSize.zero
            scales.width = abs(target.width / rect.width)
            scales.height = abs(target.height / rect.height)

            switch self {
                case .aspectFit:
                    scales.width = min(scales.width, scales.height)
                    scales.height = scales.width
                case .aspectFill:
                    scales.width = max(scales.width, scales.height)
                    scales.height = scales.width
                case .stretch:
                    break
                case .center:
                    scales.width = 1
                    scales.height = 1
            }

            var result = rect.standardized
            result.size.width *= scales.width
            result.size.height *= scales.height
            result.origin.x = target.minX + (target.width - result.width) / 2
            result.origin.y = target.minY + (target.height - result.height) / 2
            return result
        }
    }
}
